version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - test-flow:
          filters:
            tags:
              only: /.*/

jobs:
  test-flow:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            python -m venv ~/venv
      - run:
          name: Install dependencies
          command: |
            . ~/venv/bin/activate
            pip install -U pip
            pip install --progress-bar off -r requirements.txt -U -e .
      - run:
          name: Run pylint
          command: |
            . ~/venv/bin/activate
            pylint --rcfile=.pylintrc cornell tests
      - run:
          name: Run pytest
          command: |
            . ~/venv/bin/activate
            pytest
